### PR TITLE
Fixed "Packr is not a class" errors

### PR DESCRIPTION
**Pull request by grimen**
Fixed some fundamental problems with Packr module vs. class; it was basically impossible to extend the ::Packr namespace before this change. In my case I'm using Packr for a Rails extension Packr::Rails (not yet on GitHub), but this would have been a problem for any similar case.

Also moved to using autoloading as Packr should only need to be completely loaded if it's ever called within an app at all conditionally - more efficient that way.

The changes should be completely backwards compatible. :)

P.S. Great lib!

### CODE REVIEW

**Comment by jcoglan** [comment]
Could you provide more info on your problem? I've never seen the error you mention before and I'd rather not introduce an arbitrary layer of indirection (especially one requiring a custom `new` method) to work around what sounds like a bug in ActiveSupport.

Why does having a class as the root namespace make it impossible to use in Rails?

**Comment by grimen** [comment]
According to me it should work monkey-patch-wise (even though wrapping a class in a class makes no sense in no real or fictive world - though Ruby handles this as module in the end anyway somehow), but it don't work and I cannot really explain why as I probably will have to drill into the ruby core libs to find the explanation. What I do know that Packr was the first gem throwing this error in years for me, so I assume ActiveSupport is not to blame (I use many gems, so if 99%+ of them never fails to extend like this I don't consider ActiveSupport the problem). I went to look into many other libraries (I reviewed many templating libs especially) to learn how they handle it, and it seems every Bundler-friendly gem use module as namespace - and it works. I do believe the "class Packr; class X..." is the real issue here, but also if we want Packr converter to be instantiated the only way of doing this is using Packr base class as I see it, in this case I named it Packr::Engine. I think it's a reason it's the design pattern everyone are using.

The other commits dont' really need any arguments, so I guess you meant the first commit only.

**Comment by jcoglan** [comment]
Sorry for the delay, it's been a busy few months. Could you provide a demo app that shows this problem? I'm not convinced the ActiveSupport/Bundler doesn't like it simply because it's a class. Changing the main namespace from a class to a module would not be backwards-compatible so I need a little more convincing that this is the root cause of the problem.

**Comment by jcoglan** [comment]
I'm closing this due to inactivity, let me know if you have any more information.

**Pull request closed without merging**
